const MOD_TEMPLATES = {
  basic_item: {
    name: '基本アイテム MOD',
    description: 'カスタムアイテムとクラフトレシピを含む最小構成です。対応: 1.21.11 / 26.1.1',
    xml: `<xml><block type="mod_init" x="20" y="20"><field name="MOD_ID">basic_item_mod</field><field name="MOD_NAME">Basic Item Mod</field><field name="VERSION">1.0.0</field><field name="MC_VERSION">1.21.11</field><field name="MOD_SIDE">BOTH</field><field name="NO_CHEAT">FALSE</field><statement name="CONTENT"><block type="register_item"><field name="ITEM_ID">ruby</field><field name="ITEM_NAME">Ruby</field><field name="MAX_COUNT">64</field><field name="RARITY">RARE</field><field name="IS_FOOD">FALSE</field><next><block type="recipe_shaped"><field name="RESULT">ruby</field><field name="COUNT">1</field><field name="PATTERN1"> D </field><field name="PATTERN2">DED</field><field name="PATTERN3"> D </field><statement name="KEYS"><block type="recipe_key"><field name="KEY">D</field><field name="ITEM">minecraft:diamond</field><next><block type="recipe_key"><field name="KEY">E</field><field name="ITEM">minecraft:emerald</field></block></next></block></statement></block></next></block></statement></block></xml>`
  },
  magic_wand: {
    name: '魔法の杖 MOD',
    description: '右クリック時にパーティクルと効果を発動します。対応: 1.21.11',
    xml: `<xml><block type="mod_init" x="20" y="20"><field name="MOD_ID">magic_wand_mod</field><field name="MOD_NAME">Magic Wand Mod</field><field name="VERSION">1.0.0</field><field name="MC_VERSION">1.21.11</field><field name="MOD_SIDE">BOTH</field><field name="NO_CHEAT">FALSE</field><statement name="CONTENT"><block type="register_item"><field name="ITEM_ID">magic_wand</field><field name="ITEM_NAME">Magic Wand</field><field name="MAX_COUNT">1</field><field name="RARITY">EPIC</field><field name="IS_FOOD">FALSE</field><next><block type="on_item_use"><field name="ITEM_ID">magic_wand</field><statement name="ACTIONS"><block type="action_spawn_particle"><field name="PARTICLE">ENCHANTED_HIT</field><field name="COUNT">30</field><next><block type="action_apply_effect"><field name="EFFECT">SPEED</field><field name="DURATION">10</field><field name="AMPLIFIER">2</field></block></next></block></statement></block></next></block></statement></block></xml>`
  },
  custom_ore: {
    name: '鉱石追加 MOD',
    description: '鉱石、生成設定、精錬をまとめたテンプレートです。対応: 1.21.11',
    xml: `<xml><block type="mod_init" x="20" y="20"><field name="MOD_ID">mythril_ore_mod</field><field name="MOD_NAME">Mythril Ore Mod</field><field name="VERSION">1.0.0</field><field name="MC_VERSION">1.21.11</field><field name="MOD_SIDE">BOTH</field><field name="NO_CHEAT">FALSE</field><statement name="CONTENT"><block type="register_ore_block"><field name="BLOCK_ID">mythril_ore</field><field name="BLOCK_NAME">Mythril Ore</field><field name="HARDNESS">4</field><field name="RESISTANCE">4</field><field name="XP_MIN">2</field><field name="XP_MAX">5</field><field name="HAS_ITEM">TRUE</field><next><block type="register_item"><field name="ITEM_ID">mythril_ingot</field><field name="ITEM_NAME">Mythril Ingot</field><field name="MAX_COUNT">64</field><field name="RARITY">RARE</field><field name="IS_FOOD">FALSE</field><next><block type="register_ore_gen"><field name="BLOCK_ID">mythril_ore</field><field name="MIN_Y">-32</field><field name="MAX_Y">24</field><field name="VEINS_PER_CHUNK">7</field><field name="VEIN_SIZE">6</field><field name="DIMENSION">OVERWORLD</field></block></next></block></next></block></statement></block></xml>`
  },
  tools_armor: {
    name: 'ツールと防具 MOD',
    description: '素材、武器、防具セットをまとめています。対応: 1.21.11 / 26.1.1',
    xml: `<xml><block type="mod_init" x="20" y="20"><field name="MOD_ID">ruby_gear_mod</field><field name="MOD_NAME">Ruby Gear Mod</field><field name="VERSION">1.0.0</field><field name="MC_VERSION">26.1.1</field><field name="MOD_SIDE">BOTH</field><field name="NO_CHEAT">FALSE</field><statement name="CONTENT"><block type="register_item"><field name="ITEM_ID">ruby_ingot</field><field name="ITEM_NAME">Ruby Ingot</field><field name="MAX_COUNT">64</field><field name="RARITY">RARE</field><field name="IS_FOOD">FALSE</field><next><block type="item_tool"><field name="ITEM_ID">ruby_sword</field><field name="ITEM_NAME">Ruby Sword</field><field name="TOOL_TYPE">SWORD</field><field name="MATERIAL">DIAMOND</field><field name="ATTACK_DAMAGE">7</field><field name="ATTACK_SPEED">-2.2</field><next><block type="register_armor_set"><field name="ID_PREFIX">ruby</field><field name="NAME_PREFIX">Ruby</field><field name="BASE_MATERIAL">DIAMOND</field><field name="DURABILITY_MULT">28</field><field name="ENCHANTABILITY">18</field><field name="HELMET_DEF">3</field><field name="CHEST_DEF">8</field><field name="LEGS_DEF">6</field><field name="BOOTS_DEF">3</field></block></next></block></next></block></statement></block></xml>`
  },
  server_utils: {
    name: 'サーバーユーティリティ',
    description: '参加メッセージとコマンドのサーバー向け構成です。対応: 1.21.11',
    xml: `<xml><block type="mod_init" x="20" y="20"><field name="MOD_ID">server_utils_mod</field><field name="MOD_NAME">Server Utils Mod</field><field name="VERSION">1.0.0</field><field name="MC_VERSION">1.21.11</field><field name="MOD_SIDE">SERVER</field><field name="NO_CHEAT">FALSE</field><statement name="CONTENT"><block type="on_player_join"><statement name="ACTIONS"><block type="action_broadcast"><field name="MESSAGE">サーバーへようこそ</field><field name="COLOR">GOLD</field></block></statement><next><block type="register_command"><field name="COMMAND_NAME">hub</field><field name="PERMISSION">0</field><statement name="ACTIONS"><block type="command_reply"><field name="MESSAGE">ハブ機能は準備中です。</field></block></statement></block></next></block></statement></block></xml>`
  },
  client_hud: {
    name: 'クライアント HUD MOD',
    description: 'クライアント専用の GUI / HUD 系のたたき台です。対応: 1.21.11',
    xml: `<xml><block type="mod_init" x="20" y="20"><field name="MOD_ID">client_hud_mod</field><field name="MOD_NAME">Client HUD Mod</field><field name="VERSION">1.0.0</field><field name="MC_VERSION">1.21.11</field><field name="MOD_SIDE">CLIENT</field><field name="NO_CHEAT">FALSE</field><statement name="CONTENT"><block type="register_gui_screen"><field name="SCREEN_ID">client_hud</field><field name="TITLE">Client HUD</field><field name="BG_COLOR">0xAA101820</field><field name="WIDTH">256</field><field name="HEIGHT">180</field><statement name="ELEMENTS"><block type="gui_label"><field name="TEXT">Client HUD</field><field name="X">12</field><field name="Y">12</field><field name="COLOR">0xFFFFFF</field><field name="SCALE">1.5</field><field name="SHADOW">TRUE</field><next><block type="gui_progress_bar"><field name="X">12</field><field name="Y">42</field><field name="W">180</field><field name="H">10</field><field name="COLOR">0x55FF55</field><field name="VAR_NAME">progress</field></block></next></block></statement></block></statement></block></xml>`
  },
  config_pack: {
    name: '設定付き MOD',
    description: '設定値と GUI を組み合わせるベースです。対応: 1.21.11',
    xml: `<xml><block type="mod_init" x="20" y="20"><field name="MOD_ID">config_mod</field><field name="MOD_NAME">Config Mod</field><field name="VERSION">1.0.0</field><field name="MC_VERSION">1.21.11</field><field name="MOD_SIDE">BOTH</field><field name="NO_CHEAT">FALSE</field><statement name="CONTENT"><block type="register_config"><field name="CONFIG_ID">main_config</field><field name="CONFIG_NAME">Main Config</field><next><block type="config_bool"><field name="KEY">enableFeature</field><field name="DEFAULT">TRUE</field><next><block type="config_int"><field name="KEY">power</field><field name="DEFAULT">10</field></block></next></block></next></block></statement></block></xml>`
  }
};
